### ISSUE TITLE
[apiRefactor] Miscellaneous fixes

### ISSUE THREAD

**Issue by rcchen** [palantir/plottable#1952]
* `components`
  * `axis`
    * `axis.ts`
      - [x] `_requestedSpace` -> `requestedSpace` (#1979)
  * `plots`
    * `barPlot.ts`
      - [x] `barLabelsEnabled` -> `labelsEnabled` (#1953)
      - [x] `barLabelFormatter` -> `labelFormatter` (#1978)
  * `component.ts`
    - [x] Change alignment strings to an alignment class with static properties (#1955)
    - [x] `_doRender()` -> `_render()` (#1976)
  * `componentContainer.ts`
    - [x] `_addComponent(component)` -> `add(component)` (#1958)
    - [x] `_removeComponent(component)` -> `remove(component)` (#1958)
  * `table.ts`
    - [x] `addComponent(row, col, component)` -> `addComponent(component, row, col)` (#1958)
    - [x] `_removeComponent(component)` -> `removeComponent(component)`. Potentially overload this function in the future so that it can be removed by position in table as well (ie. `removeComponent(row, col)`) (#1958)
* `core`

**Comment by jtlan** [comment]
Disagree with `barAlignment`, since that makes it clearer what is being aligned and avoids confusiong with `xAlign`, `yAlign`.

**Comment by jtlan** [comment]
@rcchen This issue is done, I take it?

**Comment by rcchen** [comment]
Closing out this issue unless I come up with new things to add to it.
