### ISSUE TITLE
API Review 5/12 TODO

### ISSUE THREAD

**Issue by rcchen** [palantir/plottable#2039]
Please flesh these out if you have any more information on each of these, I wasn't here for this meeting so I don't have the context needed. If you did something, check it off and reference the pull request in parentheses after the task item. 

#### Open questions
- [ ] Should `DatasetCallback` return `void` instead of `any`? Same for other types of callbacks
- [ ] Should `Dataset` be renamed?
- [ ] Should `RenderPolicy` exist as a type, or should we just use `string`s instead?
- [ ] Do `Projector` and `AppliedProjector` need to exist?
- [ ] Does `Extent` need to exist?

#### Core
- [ ] `_timeoutMsec` exposed on `RenderPolicies.Timeout`
- [ ] Get rid of `PlotMetadata`
- [ ] `_Accessor` --> "`Accessor`", improve signature
- [ ] Delete `SelectionArea`
- [ ] Declare `type`s where they're used
- [ ] `Bounds` -> Origin + width & height vs top-left & bottom-right `Point`s
- [ ] Move `Domainer` logic to `Scale`s
- [x] `ExtentProvider` -> `ExtentsProvider` (#2052)

#### Scale
- [x] `Scale`.(on|off)Update should return `Scale` (#2036)
- [ ] `Scale._autoDomainIfAutomaticMode()` exposed
- [x] "QuantitativeScaleScale" in docstrings (#2040)
- [ ] `QuantitativeScale`.copy() should be deleted or abstract (#2031)
- [x] Remove or undeprecate `Log` scale (in favor of `ModifiedLog`) (#2032)
- [ ] Remove `_d3Scale` from `Plottable.Scale` (implementation detail)
- [ ] `innerPadding()`/`outerPadding()` on `Scales.Category`?
- [ ] `Scales.Color` lacks `copy()` and `copy()` sucks (#2031)

#### Component
- [x] hide `Component.clipPathEnabled` (#2043)
- [ ] `computeLayout()` vs `getSize()` -->  `calculateSize()`?
- [ ] `Component.render(immediately)` --> two methods
- [ ] rename `Component.redraw()`?
- [x] `Component.xAlign()`ment? (#2035)
- [ ] `Component.draw()`/`render()`/`redraw()`
- [ ] `Component.classed()`
- [ ] Remove `Component.above()` and `below()` and `merge()` -- explicitly create `Group`s when needed

#### Axis
- [ ] `TickGenerator` signature?
- [ ] remove `Axis._rescale()`
- [x] `Axis<D>.getTickValues()` should return D[] (#2047).
- [ ] `Axis.redraw()` should return Axis
- [ ] `Axes.Numeric.showEndTickLabel()` (not Labels!) (#1946).
- [x] `Components.Label.orient()` --> `orientation()` (#2033)
- [x] TitleLabel and AxisLabel remove?  Put CSS class names in Label class. (#2037)

#### Legend
- [ ] `Legend.sortFunction()` -> `compareFunction()`?
- [ ] `Legend.scale()` -> `colorScale()`, or constructor param renamed to `scale`

**Comment by jtlan** [comment]
Split into subissues.
