### ISSUE TITLE
API Review 5/13 TODO

### ISSUE THREAD

**Issue by rcchen** [palantir/plottable#2044]
#### Plottable.Plot
- [ ] _key2Plot…() -> keyToPlot…()
- [ ] Projection -> AccessorScaleBinding
- [ ] _animate and other things can become private
- [ ] _datachanged too?
- [ ] Delete generateProjectors()
- [ ] animate() -> animated()
- [ ] Plot.PlotData -> PlotElement[]?
- [ ] automaticallyAdjustYScaleOverVisiblePoints -> autoRangeY()

#### Plot.Rectangle
- [ ] Can this go away?  Do we need it for anything other than grid?

#### Plot.Grid 
- [ ] Do we need 3 accessors each for x and y?

#### Bar
- [ ] constructor() isVertical param should be stringy enum.
- [ ] Baseline(number) should take X|Y or …?
- [ ] getBars()  -> plotDataAt() and plotDataInRange() and return PlotData or ?
- [ ] Line and Area should have a Y type parameter
- [ ] Stacked -> utils methods #2051

**Comment by jtlan** [comment]
Split into subissues.
