### ISSUE TITLE
Final API Review notes

### ISSUE THREAD

**Issue by aicioara** [palantir/plottable#2261]
Feel free to break them into smaller issues

- [x] There is a POLYFILL_TIMEOUT_MSEC variable exposed in Utils.DOM.  We should probably hide this variable. (#2272)
- [x] There is a function in Plottable.Formatters that is not a Formatter. (#2272)
- [x] The parameter name to XYPlot.autoRange does not reflect the endpoint name. (#2272)
- [x] Plottable has a Configs module used for currently shutting off the warnings thrown to the console.  However, we just learned recently that this endpoint may not be used.  We may want to remove this. (#2272)
- [x] The RenderController has a setRenderPolicy function.  We might want to split this to a getter/setter combo. (#2272)
- [x] A lot of our Utils functions have the “get” prefix.  We should stick with our fluent style and remove these “get”s. (#2259)
- [x] StackedUtils’s computeStackOffsets() should not return a d3Map and likely a Utils.Map. (#2262)
- [x] StackedUtil’s computeStackExtents() has quite the number of arguments (5).  Seek to reduce this. (#2262)
- [x] ClientToSVGTranslator has a factory function with the “get” prefix in front.  We may consider renaming the factory functions to possibly “getInstance”. (#2264)
- [x] Our factory functions may want to be renamed to getInstance() (#2264)
- [x] We will need to do a documentation sweep as a large number of our exposed stuff is not well documented. (#2265)
- [x] QuantitativeScale._DEFAULT_NUM_TICKS seems like it is not used and should be deleted. (#2271)
- [x] Possibly remove the colorRange constructor parameter from InterpolatedColorScale. (#2271)
- [x] Component._getSize() should have a clearer distinction from computeLayout(). (#2059)
- [x] Component.classed() has really odd semantics.  However, it is very closely written to D3’s API. (#2219)
- [x] Axis.gutter maybe should be worded to margin.  The documentation surrounding should point to the endpoint more clearly. (#2266)
- [x] The formatter constructor argument on Axes can probably be removed. (#2266)
- [x] Legend.maxEntriesPerRow should have a more reflected parameter name (#2267)
- [x] Legend.symbolFactoryAccessor does not take in a Plottable Accessor. (#2267)
- [x] InterpolatedColorLegend has an orientation constructor argument that is optional, which is inconsistent. (#2267)
- [x] The Animators all extend from Plots.Animator which seems really odd. (#2269)
- [x] The main Animator that a bunch of the Plots use is called Animators.Base, which is not a good name. (#2269)
- [x] Dispatcher has an instance variable called _event2Callback.  We should change the “2" to a “To" (#2268)
- [x] Dispatchers.Mouse.lastMousePosition should be explicitly typed to Point (#2268)
- [x] Interactions.Key has “onKey” endpoints that should probably be renamed to something like “onKeyPress” (#2268)
- [x] PanZoomInteraction has an exposed PIXELS_PER_LINE that should be looked at. (#2268)
- [x] Interactions.Drag has a constrainToComponent() endpoint that should be renamed so that dragInteraction.constrainToComponent() more looks like a getter (#2268)

**Comment by aicioara** [comment]
Split into subissues
