### ISSUE TITLE
Legend Refactor

### ISSUE THREAD

**Issue by aicioara** [palantir/plottable#2267]
- [x] Legend.maxEntriesPerRow should have a more reflected parameter name (PR: #2283)
- [x] Legend.symbolFactoryAccessor does not take in a Plottable Accessor (PR: #2309).
- [x] InterpolatedColorLegend has an orientation constructor argument that is optional, which is inconsistent. (PR: #2284)

**Comment by bluong** [comment]
All checks.  CLose!
