### ISSUE TITLE
Small Refactor issues

### ISSUE THREAD

**Issue by aicioara** [palantir/plottable#2272]
- [x] There is a POLYFILL_TIMEOUT_MSEC variable exposed in Utils.DOM.  We should probably hide this variable. (PR: #2293)
- [x] There is a function in Plottable.Formatters that is not a Formatter. (PR: #2278)
- [x] The parameter name to XYPlot.autoRange does not reflect the endpoint name (PR: #2295).
- [x] The RenderController has a setRenderPolicy function.  We might want to split this to a getter/setter combo. (PR: #2280)

**EDIT**
<del>Plottable has a Configs module used for currently shutting off the warnings thrown to the console.  However, we just learned recently that this endpoint may not be used.  We may want to remove this. (PR: #2279)</del>

**Comment by jtlan** [comment]
@bluong has the last checkbox on his PR, so I'm reassigning to him.

**Comment by bluong** [comment]
Got all the checkboxes
